networks:
  kafka:
    external: false

volumes:
  kafka-data:
    external: false

services:
  kafka:
    image: apache/kafka:latest
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:9094
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_NUM_PARTITIONS=3
    volumes:
      - kafka-data:/var/lib/kafka/data
      # - /etc/kafka/secrets:...
      # - /mnt/shared/config:...
    networks:
      - kafka
    restart: unless-stopped

  redpanda:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - 8050:8080
    environment:
      - KAFKA_BROKERS=kafka:9094
    networks:
      - kafka
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui
    # container_name: kafka-ui
    ports:
      - 8080:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9094
      - DYNAMIC_CONFIG_ENABLED=true
    networks:
      - kafka
    restart: unless-stopped
